name: CSS
on: [push, pull_request]
env:
  CI: true

jobs:
  css:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 3

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Build CSS
        run: npm run css
